# 异常与自定义异常类

## 异常

>* 异常指在程序运行期间使程序中断的指令，就是异常。
>
>* java中异常的最大父类（根类）是Throwable类
>  * Error错误
>  * Exception异常
>    * 运行时异常：`CheckedException`
>    * 检查时异常：`RuntimeException`程序代码会自动检查代码的合理性
>  * 异常不一定会触发，异常触发会使程序中断，JVM在执行程序时，异常信息由JVM打印到控制台。
>  * 异常处理：
>    * 捕获异常
>    * 抛出异常
>

## 抛出/捕获异常的几种方式：

>### 在方法体内使用`try-catch-finally语句`处理方法本身所产生的异常。**`处理异常，捕获异常`**
>
>```java
>try{
>	...Statement...
>}catch(Exception e){
>    //打印堆栈使用轨迹或打印异常提示信息
>    e.PrintStackTrace();
>}finally{
>	//无论try语句是否会发生异常都会执行finally语句
>    System.out.println("始终都会执行的语句内容");
>}
>```
>
>* `面试题：关于对finally语句的理解`
>
>  ```java
>  package exception;
>  
>  /**
>   * @author MoFany-J
>   * @date 2022/10/8
>   * @description Demo
>   */
>  public class Demo {
>      /**
>       * 有这样一个方法请问该方法的返回值为？
>       * */
>      public boolean someMethod(){
>          try{
>              return true;
>          }catch (Exception e){
>              e.printStackTrace();
>          }finally {
>              return false;
>          }
>      }
>  
>      public static void main(String[] args){
>          //返回值始终为：false
>          System.out.println(new Demo().someMethod());
>      }
>  }
>  ```
>
>  ```properties
>  false
>  
>  Process finished with exit code 0
>  ```
>
>* `JDK7提出的异常链：`
>
>  ```java
>  package exception;
>  
>  import java.io.UnsupportedEncodingException;
>  import java.util.Scanner;
>  
>  /**
>   * @author MoFany-J
>   * @date 2022/10/8
>   * @description MainClass
>   */
>  public class MainClass {
>      public static void main(String[] args) {
>          int a, b, c = 0;
>          System.out.print("请输入分子：");
>          a = new Scanner(System.in).nextInt();
>          System.out.print("请输入分母：");
>          b = new Scanner(System.in).nextInt();
>          String str1 = "Hello World!";
>          System.out.print("请输入指定编码：");
>          String encoding = new Scanner(System.in).nextLine();
>          
>          //JDK7开始自带的异常链,即分母即不能为0且
>          try {
>              String str2 = new String(str1.getBytes(), encoding);
>              c = a / b;
>              System.out.println("字符串str2内容为：" + str2.toString());
>              System.out.println("a/b=" + c);
>          } catch (UnsupportedEncodingException | ArithmeticException e) {
>              //判断异常类对象e是不是异常类UnsupportedEncodingException的实例
>              if (e instanceof UnsupportedEncodingException) {
>                  System.out.println("########《异常提示》###########\r\n不存在的编码方式！");
>              }
>              //判断异常类对象e是不是异常类ArithmeticException的实例
>              if (e instanceof ArithmeticException) {
>                  System.out.println("########《异常提示》###########\r\n分母（除数）不能为零！");
>              }
>          }
>      }
>  }
>  ```
>
>  ```properties
>  请输入分子：0
>  请输入分母：0
>  请输入指定编码：gbk
>  ########《异常提示》###########
>  分母（除数）不能为零！
>  
>  Process finished with exit code 0
>  ```
>
>* `使用try-finally结构完成资源的关闭`（前提是已完全了解try语句块内不会发生异常）
>
>  ```java
>  /**
>   * BufferedReader类中close()方法的源码
>   */
>  public void close() throws IOException {
>  	//语句同步
>      synchronized (lock) {
>  		if (in == null)
>  			return;
>  		try {
>  			in.close();
>  		} finally {
>  			in = null;
>  			cb = null;
>  		}
>  	}
>  }
>  ```
>
>### 在方法声明的头部使用`throws语句`将多个异常类送往上一层调用机构去处理。**`抛出异常类（向上级或方法调用点抛出）`**
>
>>踢皮球策略：方法体上抛出异常交给方法调用者去处理，若方法调用者也不处理该异常则继续由当前方法显示的抛出该异常类，
>>
>>**项目测试的时候抛出异常，项目开发的时候一定要处理异常！（由最终调用者去处理该异常）**
>
>```java
>/**
> * 书写规范
> */
>public void aMethod() throws NullPointerException,ClassNotFoundException{
>	
>    ...Method body...
>}
>```
>
>### 在方法体内使用`throw语句`将单个异常类对象送往上一层调用机构去处理。**`抛出异常类对象（向上级或方法调用点抛出）`**
>
>>将方法内部的异常类对象抛给方法的调用者，若调用者不处理该异常，则又由调用者将该异常隐式的抛给上级直到抛给JVM去处理执行并打印堆栈使用轨迹。
>
>```java
>/**
> * 书写规范
> */
>public void aMethod(){
>    
>	...Statement...
>        
>    if(...){
>        //向调用点抛出异常类对象
>		throw new XxxException();
>    }
>}
>```
>
>### 自动关闭资源的`try`语句，结合`catch`语句来写
>
>* 在方法体内使用`try-with-resources（自动资源管理语句）`可以实现打开资源的自动关闭，以防止资源未关闭而引起的异常。`(并不是所有资源都可以自动关闭，而是只有实现了java.lang.AutoCloseable接口的资源才能实现自动关闭)`
>
>```java
>//自动关闭资源
>try(
>//创建要使用的资源
>){
>
>    //可能会发生异常的代码块
>    ...Statement...
>        
>}catch(Exception e){
>    
>	System.out.println("发生异常！");
>}
>```
>
>### 方法声明部分使用大的异常类去接收小的异常类对象
>
>#### 接口的实现类中重写的接口方法头部的异常类可以是接口中定义的抽象方法声明部分异常类的子类
>
>#### 但也可以反向操作，即运行时异常对应运行时异常，检查时异常对应检查时异常（可以向上或向下转型）

## 用户自定义异常

>### 用户自定义异常类的注意事项：
>
>- [x] **用于自定义异常类也是一个类**。
>- [ ] **定义足够的异常类是构建一个稳定且完善的应用系统的重要基础之一**。
>- [x] ==**用户自定义异常类必须是`Throwable类`的直接或间接子类，但是Java推荐用户自定义的异常类以`Exception类`为其直接父类。（也可以使用一个已存在的系统异常类或用户自定义异常类为其父类）**==
>- [x] ==**习惯上在自定义异常类中加入两个构造器，分别为`无参构造器`与`含有字符串形参的构造器`。**==
>- [x] ==**用户自定义异常类不能由系统自动抛出，而应该使用`throw语句`去定义何种情况下会产生此异常对应的错误，然后在利用`throw语句`去抛出该异常类的对象。**==
>- [x] ==**在自定义异常类时我们应该提供两个构造器：无参构造器与只含一个字符串参数的构造器。**==
>
>### 用户自定义异常类的实现：
>
>```java
>package exception;
>
>/**
> * @author MoFany-J
> * @date 2022/10/8
> * @description CustomException 自定义输出异常类
> */
>class CustomException extends Exception{
>
>    /**
>     * 无参构造器
>     */
>    public CustomException() {
>        super();
>    }
>
>    /**
>     * 只含一个字符串参数的构造器
>     */
>    public CustomException(String message) {
>        super(message);
>    }
>}
>```
>
>